### ISSUE TITLE
Create documentation for Wizard Component

### ISSUE THREAD

**Issue by gsi-chao** [gsi-chao/gsi-ui#308]
Create documentation for Wizard Component

**Comment by gsi-lozano** [comment]
started 02/24/2020 10:00am

**Comment by gsi-lozano** [comment]
ended 02/25/2020 17:00pm
After a research for a documentation tool, some libraries were tested:
- Styleguidist: this one allows to render typscript inside mdx (documentation markup files with steroids), it creates a documentation with side menu, and code highlighting, but removes component's styles, and put their own style. This is an issue in the community right now.
- Docz: The configuration for this library is a little bit tricky, when it comes to use typescripts, and at the end, the application throws a 'window' exception, this happens because the library use gatsby as a generator, and the 'window' only exist on browsers, not for all node apps.
- MDX-docs: This one is for Next.js apps.
